# 公開するページのURL
baseURL = "https://naokomada.github.io/blog"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = "blog"

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "komada naoki"
    bio = "エンジニャー"
    avatar = ""

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#32cd32"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "naokomada"
  github = "naokomada"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

